### ISSUE TITLE
Incompatible JS version upon startup

### ISSUE THREAD

**Issue by arbesfeld** [redbooth/react-native-auto-updater#3]
What happens in this scenario?
1. User downloads/caches a JS bundle for v1.0 of the app.
2. User installs v1.1 of the app from the app store.

Will the app use the old JS bundle from the cache? What if it is incompatible with the newer native code?

**Comment by rahuljiresal** [comment]
We ship a JS bundle with the app. So when a user installs a version from App Store, it comes with the JS code that is compatible with the native code. Since the use has already downloaded that certain JS bundle, it won't be downloaded again, until it is updated on the server.

This is a very primitive approach to the whole update process. Ideally, all JS files should have a minimum compatibility and maximum compatibility versions associated with them. This can be done very gracefully with a small backend service with an endpoint that accepts the app's version and points to the right latest JS code compatible with it.

**Comment by arbesfeld** [comment]
I understand that a JS bundle is shipped with the app. I might be mistaken, but it seems like this system will default to using a previously cached version of JS. When I upgrade the version of my app, it doesn't clear the Library cache, so it may use old JS rather than the bundled JS.

**Comment by rahuljiresal** [comment]
Yes, you're right. The app needs to contain (and consider) the metadata of the JS bundle shipped with the app. This is a bug. The easiest way I can think of to fix it is to ship the app with the metadata file, and check the shipped version with the cached one. What say?

**Comment by arbesfeld** [comment]
I think that would work. Another solution would be to store the metadata on the current loaded JS, and check at startup whether the JS is compatible with the native version.

**Comment by rahuljiresal** [comment]
The problem with that is the metadata only has `minContainerVersion` field, and no `maxContainerVersion` field. It will still be compatible with the new app. We cannot introduce the `maxContainerVersion` field coz we don't know when the app will become incompatible in future.

So yes, the first approach will work.

**Comment by rahuljiresal** [comment]
This is fixed with PR #10
