### ISSUE TITLE
Atomicity of an update

### ISSUE THREAD

**Issue by arbesfeld** [redbooth/react-native-auto-updater#4]
It looks like all JS code is stored at `Library/JSCode/main.jsbundle`, which requires that we delete the bundle upon download of a new bundle. https://github.com/aerofs/react-native-auto-updater/blob/master/Pod/Classes/ReactNativeAutoUpdater.m#L400

This could lead to cases where the value of the `__tempCodeVersion` NSUserDefaults is invalid, because there is no code at the expected file location.

One solution would be to assign a unique identifier to each JS bundle, and store bundles at unique paths based on these identifiers.

**Comment by zackify** [comment]
If you stored each version you could make it so if an exception occurs maybe prompt the user to revert to an older version?

**Comment by rahuljiresal** [comment]
@arbesfeld yes, you're right. Saving each version adds to the complexity, but it can be done. Let me look into it sometime next week. But I would assume if the delete is successful, the file write would be successful too. Now the only thing in question is, as @zackify mentioned, if the new JS code is bad/buggy, then we should automatically revert to the old one.

This, also, is a non-trivial thing, because it is really hard to find out what kind of exceptions the new JS code would have. Also, this would need making changes to the ReactNative code. If the JS has compiler errors, we should revert, but finding out if it has compiler errors is non-trivial. On the other hand, if the new JS has runtime errors/exceptions, they could be because multitude of reasons.

Having said this, I'll look into this whole thing in more detail over the next week.

**Comment by rahuljiresal** [comment]
This is also fixed with PR #10
